name: Build and Test Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    - name: Cache Maven dependencies (optional)
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Run tests with Maven
      run: mvn test

    - name: Package Spring Boot Application
      run: mvn package -DskipTests=true

    - name: Upload Artifact (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: gh-action-demo
        path: target/*.jar
